# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-04 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Topic'),
            preserve_default=False,
        ),
    ]
