# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-04 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
