# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-10 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text2',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
